### ISSUE TITLE
Importing music_db

### ISSUE THREAD

**Issue by mello0** [Alo81/YesWeDo#43]
I tried to import the music_db.prc file into YWD to use the songs I added via sm5shmusic into spirit battles, but the ID's do not appear in the dropdown menu. Should I type in the IDs manually, or is this a bug?

**Comment by Alo81** [comment]
Howdy bud.  Not a bug, right now the titles are not populated through the music DB file, its pulled from all songs that have been used in spirit battles.  

You can type the IDs in manually and they should work after you save, then if you load that spirit DB again in the future, it will show up in the list of IDs as well.

**Comment by Alo81** [comment]
I'll update the label on this to Enhancement and keep it in mind as I'm adding new functionality.

**Comment by mello0** [comment]
Alrighty, thankyu

**Comment by Alo81** [comment]
Hey bud, wanted to ping you that the latest update will pull all ID's from the ui_bgm_db.prc
